/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <button1_aliases.h>
#include <button1.h>
#include <led1_aliases.h>
#include <led1.h>
#include <led2_aliases.h>
#include <led2.h>
#include <button2_aliases.h>
#include <button2.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
